accounts/urls.py
from django.urls import path
from .views import CustomLoginView
from . import views


urlpatterns = [
    path('login/', CustomLoginView.as_view(), name='login'),
    path('profile/', views.profile, name='profile'),
    path('signout/', views.signout, name='logout'),
]

orchestral_projects/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.list, name='list'),
    path('<int:id>', views.detail, name='detail'),
]

sistema_inscripcion/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),

    # Autenticación y usuarios
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),

    # CRUD de estudientes
    path('students/', include(('students.urls', 'students'), namespace='students')),
    
    # Panel de visualización
    path('dashboard/', include(('dashboard.urls', 'dashboard'), namespace='dashboard')), 

    # CRUD de instrumentos
    path('instruments/', include(('instruments.urls', 'instruments'), namespace='instruments')),

    # CRUD de proyectos orquestales
    path('orchestral_projects/', include(('orchestral_projects.urls', 'orchestral_projects'), namespace='orchestral_projects')),

]

orchestral_projects/models.py
from django.db import models

# Create your models here.
class OrchestralProject(models.Model):
    code = models.CharField(max_length=20)
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.code + ' - ' + self.name

orchestral_projects/forms.py
from django import forms
from django.forms import ModelForm
from .models import OrchestralProject


class OrchestralProjectForm(ModelForm):
    class Meta:
        model = OrchestralProject
        fields = ['code', 'name']
        widgets = {
            'code': forms.TextInput(attrs={
                'class': 'block w-full p-2.5 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-sm focus:ring-blue-500 focus:border-blue-500',
                'placeholder': 'Ej: INICIAL-001',
                'required': 'true' # Hace el campo HTML requerido
            }),
            'name': forms.TextInput(attrs={
                'class': 'block w-full p-2.5 text-gray-900 border border-gray-300 rounded-lg bg-gray-50 text-sm focus:ring-blue-500 focus:border-blue-500',
                'placeholder': 'Ej: Orquesta Sinfónica Juvenil',
                'required': 'true'
            }),
        }

orchestral_projects/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from academic_period.models import AcademicPeriod, DetailAcademicInscription
from .forms import OrchestralProjectForm
from .models import OrchestralProject
from django.db.models import Count, Q


@login_required
def list(request):
    # projects = OrchestralProject.objects.all()

    projects = OrchestralProject.objects.annotate(
        inscripciones_activas=Count(
            'detailacademicinscription',
            filter=Q(detailacademicinscription__id_academic_period__is_active=True)
        )
    )
    
    if request.method == 'GET':
        return render(request, 'orchestral_projects/orchestral_projects_list.html', {
            'form': OrchestralProjectForm,
            'projects': projects
        }) 
    else:
        try:
            form = OrchestralProjectForm(request.POST)
            new_project = form.save(commit=False)
            new_project.save()
            return redirect(reverse('orchestral_projects:list'))
        except ValueError:
            return render(request, 'orchestral_projects/orchestral_projects_list.html', {
                'form': OrchestralProjectForm,
                'error': 'Ha habido un error al registrar el nuevo proyecto.'
            }) 
        

@login_required
def detail(request, id):
    orchestral_project = get_object_or_404(OrchestralProject, id=id)    
    inscriptions = DetailAcademicInscription.objects.filter(
            id_orchestral_project=orchestral_project, 
            id_academic_period__is_active=True
        )
    
    period_active = AcademicPeriod.objects.filter(is_active=True).first()

    return render(request, 'orchestral_projects/orchestral_project_detail.html', {
        'orchestral_project': orchestral_project,
        'inscriptions': inscriptions,
        'academic_period': period_active
    }) 

orchestral_projects/templates/orchestral_projects/orchestral_project_detail.html
{% extends 'base.html' %}
{% load static %}

{% block current_page %}Estudiantes del Proyecto Orquestal{% endblock %}

{% block content %}

   
<div class="max-w-6xl mx-auto bg-white/50 shadow-lg rounded-lg p-8 mt-4">
    <h2 class="text-2xl font-bold text-gray-900 text-center mb-8">
        Proyecto: {{ orchestral_project.name }} - Año escolar {{ academic_period }}
    </h2>

    <h1>Listado de estudiantes inscritos</h1>
    <div class="bg-white/60 p-6 rounded-lg shadow-md overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50/60"> {# También puedes hacer el thead semitransparente #}
                <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nombre del alumno</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Cátedra donde está inscrito</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Fecha de inscripción</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Periodo escolar</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Detalle</th>
                </tr>
            </thead>
            <tbody class="bg-white/60 divide-y divide-gray-200"> {# Y el tbody un poco menos opaco #}
                {% for i in inscriptions %}
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{i.id_student}}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{i.id_instrument }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{ i.inscription_date }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{ i.id_academic_period }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                            <a href="{% url 'students:detail' i.id_student.id %}" class="text-blue-600 hover:text-blue-800" title="Ver detalle">
                                <i class="fas fa-eye"></i>
                            </a>
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="flex justify-center mt-4">
            <a href="#" class="text-gray-500 hover:text-pink-600 text-3xl">
                <i class="fas fa-chevron-circle-down"></i>
            </a>
        </div>
    </div>

</div>

{% endblock %}

orchestral_projects/templates/orchestral_projects/orchestral_projects_list.html
{% extends 'base.html' %}
{% load static %}

{% block current_page %}Proyectos del Núcleo{% endblock %}

{% block content %}

    <h1>Registrar Proyecto Orquestal</h1>
  
    <form action="{% url 'orchestral_projects:list' %}" method="post" >
    {% csrf_token %}

        <div class="flex flex-col md:flex-row md:items-end md:space-x-4 gap-4">
            <div class="flex-1 min-w-0"> {# flex-1 permite que el item crezca, min-w-0 para evitar desbordamiento #}
                <label for="{{ form.code.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Código referencial del proyecto</label>
                {{ form.code }}
            </div>

            <div class="flex-1 min-w-0">
                <label for="{{ form.name.id_for_label }}" class="block mb-2 text-sm font-medium text-gray-900 dark:text-white">Nombre del proyecto</label>
                {{ form.name }}
            </div>

            {# Botón #}
            <div class="self-end md:self-auto"> {# self-end para alinear el botón con la base de los inputs en móviles, md:self-auto para deshabilitarlo en md #}
                <button type="submit" class="w-full md:w-auto text-white bg-gradient-to-r from-cyan-500 to-blue-500 hover:bg-gradient-to-bl focus:ring-4 focus:outline-none focus:ring-cyan-300 font-medium rounded-lg text-sm px-5 py-2.5 text-center">Registrar nuevo proyecto</button>
            </div>

            {% if form.errors %} 
                {% for field, errors in form.errors.items %}
                    {% for error in errors %}
                        <p class="text-red-500 text-sm mt-1">{{ error }}</p>
                    {% endfor %}
                {% endfor %}
            {% endif %}

        </div>
    </form>

    <br>

    <h1>Listado de Proyectos</h1>
    {# Tabla de Proyectos #}
    {# Clases modificadas: bg-white/80 para la tabla #}
    <div class="bg-white/60 p-6 rounded-lg shadow-md overflow-x-auto">
        <table class="min-w-full divide-y divide-gray-200">
            <thead class="bg-gray-50/60"> {# También puedes hacer el thead semitransparente #}
                <tr>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">ID</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Nombre del Proyecto</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Cantidad de Alumnos Activos en el año escolar en curso</th>
                    <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Opciones</th>
                </tr>
            </thead>
            <tbody class="bg-white/60 divide-y divide-gray-200"> {# Y el tbody un poco menos opaco #}
                {% for p in projects %}
                    <tr>
                        <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">{{p.code}}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">{{p.name}}</td>
                        <td class="px-6 py-4 whitespace-nowrap stext-sm text-gray-900">{{ p.inscripciones_activas }}</td>
                        <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-900">
                            <a href="{% url 'orchestral_projects:detail' p.id %}" class="text-blue-600 hover:text-blue-800" title="Ver detalle">
                                <i class="fas fa-eye"></i>
                            </a>  
                        </td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        <div class="flex justify-center mt-4">
            <a href="#" class="text-gray-500 hover:text-pink-600 text-3xl">
                <i class="fas fa-chevron-circle-down"></i>
            </a>
        </div>
    </div>

{% endblock %}